name: Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '12.x'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.1
          run_install: false
      - name: Determine pnpm cache directory
        id: pnpm-cache
        run: |
          echo "::set-output name=dir::$(pnpm config get cache)"
      - name: Restore pnpm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pnpm-cache.outputs.dir}}
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run unit tests
        run: pnpm install && pnpm test

  action-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '12.x'
      - name: Setup rush
        uses: advancedcsg-open/actions-rush@v1.4.1
        with:
          working-directory: 'test/data'
      - name: Rush build / publish jFrog
        uses: ./
        with:
          version-policy: modules
          working-directory: 'test/data'
